language: php

php:
  - 7.2
  - 7.3

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - composer update --no-interaction $PREFER_LOWEST

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
