language: php

php:
  - 7.2
  - 7.3
  - 7.4
  # until PHPUnit upgrade allow PHP 7.4 to fails
  allow_failures:
    - php: 7.4

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

sudo: false

before_script:
  - composer update --no-interaction $PREFER_LOWEST

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
